source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'
inhibit_all_warnings!


target 'SunnyNavigation_Example' do
    
  pod 'SunnyNavigation', :path => '../'
  
end

target 'SunnyNavigation_Tests' do

end
